//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemstonesBusinessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PBH
    {
        public int MaCT_PBH { get; set; }
        public Nullable<int> MaPhieuBanHang { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> SoLuongSPHienTai { get; set; }
        public Nullable<double> DonGiaSPHienTai { get; set; }
        public string PhuongThuc { get; set; }
        public Nullable<double> DonGiaNhapSPHienTai { get; set; }
    
        public virtual PHIEUBANHANG PHIEUBANHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
