//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemstonesBusinessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PDV
    {
        public int MaCT_PDV { get; set; }
        public Nullable<int> MaPhieuDichVu { get; set; }
        public Nullable<int> MaDichVu { get; set; }
        public Nullable<double> DonGiaDichVu { get; set; }
        public Nullable<double> ChiPhiRieng { get; set; }
        public Nullable<double> DonGiaDuocTinh { get; set; }
        public Nullable<int> SoLuongDichVu { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<double> TienTraTruoc { get; set; }
        public Nullable<double> TienConlai { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<int> TinhTrangCT_PDV { get; set; }
    
        public virtual PHIEUDICHVU PHIEUDICHVU { get; set; }
        public virtual DICHVU DICHVU { get; set; }
    }
}
