//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemstonesBusinessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVT()
        {
            this.BAOCAOTONKHOes = new HashSet<BAOCAOTONKHO>();
            this.LOAISANPHAMs = new HashSet<LOAISANPHAM>();
        }
    
        public int MaDVT { get; set; }
        public string TenDVT { get; set; }
        public Nullable<int> TrangThaiDVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOTONKHO> BAOCAOTONKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAISANPHAM> LOAISANPHAMs { get; set; }
    }
}
