//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemstonesBusinessSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GemstonesEntities : DbContext
    {
        public GemstonesEntities()
            : base("name=GemstonesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAOTONKHO> BAOCAOTONKHOes { get; set; }
        public virtual DbSet<CT_PBH> CT_PBH { get; set; }
        public virtual DbSet<CT_PDV> CT_PDV { get; set; }
        public virtual DbSet<CT_PMH> CT_PMH { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<DVT> DVTs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUBANHANG> PHIEUBANHANGs { get; set; }
        public virtual DbSet<PHIEUDICHVU> PHIEUDICHVUs { get; set; }
        public virtual DbSet<PHIEUMUAHANG> PHIEUMUAHANGs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
    }
}
