//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemstonesBusinessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDICHVU()
        {
            this.CT_PDV = new HashSet<CT_PDV>();
        }
    
        public int MaPhieuDichVu { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayLapPhieuDichVu { get; set; }
        public Nullable<int> TongSoLuongDichVu { get; set; }
        public Nullable<double> TongThanhTien { get; set; }
        public Nullable<double> TongTienTraTruoc { get; set; }
        public Nullable<double> TongTienConLai { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> TinhTrangPDV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PDV> CT_PDV { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
