//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemstonesBusinessSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.BAOCAOTONKHOes = new HashSet<BAOCAOTONKHO>();
            this.CT_PBH = new HashSet<CT_PBH>();
            this.CT_PMH = new HashSet<CT_PMH>();
        }
    
        public int MaSanPham { get; set; }
        public Nullable<int> MaLoaiSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> DonGiaBan { get; set; }
        public Nullable<int> TongSoLuongTon { get; set; }
        public string HinhAnhSanPham { get; set; }
        public Nullable<int> TrangThaiSanPham { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOTONKHO> BAOCAOTONKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PBH> CT_PBH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PMH> CT_PMH { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
